[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
serde = { version = "1.0.203", features = ["derive"] }
diesel = { version = "2.0.0", features = ["mysql"] }
dotenv = "0.15.0"