version: '3.9'

services:
  db:
    image: mysql:8.4.0
    container_name: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      backend:
        ipv4_address: ${DB_IP}

  migration:
    build:
      context: ./docker/migration
      dockerfile: Dockerfile
    container_name: migration
    depends_on:
      - db
    tty: true
    environment:
      # DATABASE_URLはsqlxが参照する接続先の環境変数
      DATABASE_URL: ${DATABASE_URL}
    networks:
      backend:
        ipv4_address: ${SQLX_IP}
    volumes:
      - ./migrations:/migrations

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1

volumes:
  db-data:
