env_files = [".env"]

[tasks.create-migration-file]
description = '''
Up/Downのマイグレーションファイルを新規で作成します。

実行方法は以下です。
1) cargo make create-migration-file [migration_name]
2) makers create-migration_file [migration_name]

※ migration_name は任意の名前を指定してください。
'''
command = "docker"
args = ["compose", "exec", "migration", "sqlx", "migrate", "add", "-r", "${@}"]

[tasks.run-migration]
description = '''
作成済みのマイグレーションファイルをDBへ適用します。
言い換えるのであればUPファイルを順番に適用します。

実行方法は以下です。
1) cargo make run-migration
2) makers run-migration
'''
command = "docker"
args = ["compose", "exec", "migration", "sqlx", "migrate", "run"]

[tasks.rollback-migration]
description = '''
テーブルのスキーマバージョンを一つ戻します。
全てのバージョンを戻すことはなく、直前の一つを戻すのみです。

実行方法は以下です。
1) cargo make rollback-migration
2) makers rollback-migration
'''
command = "docker"
args = ["compose", "exec", "migration", "sqlx", "migrate", "revert"]

[tasks.redo-migration]
description = '''
Up -> Down -> Upの順番にマイグレーションを実施します。
Up/Downが正しく適用できることを証明するためのテストの意味も大きいです。

実行方法です。
1) cargo make redo-migration
2) makers redo-migration
'''
script = '''
docker compose exec migration sqlx migrate run
docker compose exec migration sqlx migrate revert
docker compose exec migration sqlx migrate run
'''

[tasks.diesel-setup]
description = "Dieselの初期設定を行います。"
command = "diesel"
args = ["setup", "--database-url", "${DB_URL_FROM_APP}"]

[tasks.diesel-sync]
description = "DieselのスキーマファイルをDBと同期します。"
script = "diesel print-schema --database-url ${DB_URL_FROM_APP} > src/schema.rs"